### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by Vvdinosaur** [kevinlin311tw/CDCL-human-part-segmentation#10]
when i run "python3 inference_15parts.py --scale=1" , error happens like:

Traceback (most recent call last):
  File "inference_15parts.py", line 200, in <module>
    model = get_testing_model_resnet101()
  File "D:\body\body\model_simulated_RGB101.py", line 456, in get_testing_model_resnet101
    C1, C2, C3, C4, C5 = ResNet101_graph(img_input, None)
  File "D:\body\body\model_simulated_RGB101.py", line 250, in ResNet101_graph
    x = conv_block(x, 3, [64, 64, 256], stage=2, block='a', strides=(1, 1))
  File "D:\body\body\model_simulated_RGB101.py", line 208, in conv_block
    x = BatchNormalization(epsilon=eps, axis=bn_axis,name=bn_name_base + '2a')(x)
  File "D:\Python3.6\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "D:\Python3.6\lib\site-packages\keras\layers\normalization.py", line 99, in build
    str(input_shape) + '.')
ValueError: Axis 1 of input tensor should have a defined dimension but the layer received an input with shape (None, None, None, 64).

Has anyone been in the same situation like this?

**Comment by rohitpaul23** [comment]
In line 208, check whats the value of bn_axis used
